### ISSUE TITLE
 `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by LoadStar822** [metaphysicser/RaMA#1]
I followed the tutorial and installed RaMA using Conda, but the following error occurred:

`RaMA`
` -h RaMA: /usr/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by RaMA) `
`RaMA: /usr/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by RaMA)`

Additionally, I find it quite inconvenient to enter the `RaMA` command.

**Comment by pinglu-zhang** [comment]
I have resolved this issue by recompiling the executable file on an older kernel version of Linux. The problem was due to compatibility issues with the glibc version on newer systems, which caused the errors related to GLIBC_2.32 and GLIBC_2.34 not being found. By using an older kernel version for recompilation, the executable is now compatible with a wider range of Linux distributions.

Thank you for reporting this issue and for your patience. Your feedback has helped improve the software’s usability across different environments. If you encounter any other issues or have further suggestions, please let me know!

**Comment by LoadStar822** [comment]
Thank you so much for taking the time to resolve the issue I encountered and for providing a detailed explanation of the cause and solution. Your effort to recompile the executable on an older kernel version, making it compatible with a wider range of Linux distributions, is incredibly helpful for both me and other users. Your support and dedication have greatly contributed to improving the software’s usability. Thank you again for helping me resolve this issue!
